# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-29 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employeetask', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetask',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
