# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-29 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeetask', '0003_employeetask_field_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeetask',
            old_name='field_name',
            new_name='time',
        ),
    ]
